{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-kube-dns
  namespace: "{{ .Release.Namespace }}"
spec:
  egress:
    - to:
      - namespaceSelector: {} # all namespaces
      ports:
        - port: 53
          protocol: UDP
  podSelector: {} # all pods in Release namespace
  policyTypes:
    - Egress
{{- end }}
