{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-istio-enabled-pods
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            istio-sidecar.istio.io/inject: true
  egress:
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            istio-sidecar.istio.io/inject: true
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}