{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-istio-injected-pods
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            istio-sidecar.istio.io/inject: "true"
      ports:
        - port: 15012
          protocol: TCP
  podSelector:
    matchLabels:
      app: istiod
  policyTypes:
    - Ingress
    - Egress
{{- end }}
