{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-internal-traffic-to-egateway{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - namespaceSelector: {}
  podSelector:
    matchLabels:
      istio: egressgateway
  policyTypes:
    - Ingress
{{- end }}
