{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-scraping
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
        - namespaceSelector: {} # all namespaces for now
      ports:
        - port: PROMETHEUS_PORT
          protocol: TCP
  podSelector: {} # all pods
  policyTypes:
    - Ingress
{{- end }}
