{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-gateway-allow-external-traffic
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - {}
  podSelector:
    matchLabels:
      istio: ingressgateway
      operator.istio.io/component: IngressGateways
  policyTypes:
    - Ingress
{{- end }}