{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-webhook{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: istiod
  ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
      - port: 15017
        protocol: TCP
      - port: 8080
        protocol: TCP
  policyTypes:
    - Ingress
{{- end }}
