{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-external-traffic-to-gateway
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
  podSelector:
    matchLabels:
      istio: ingressgateway
  policyTypes:
    - Ingress
{{- end }}
