{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-allow-webhook-api
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: istiod
      istio: pilot
  ingress:
    - from:
      - ipBlock:
          cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
          {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
          # ONLY Block requests to cloud metadata IP
          except:
          - 169.254.169.254/32
          {{- end }}
      ports:
        - port: 443
          protocol: TCP
  policyTypes:
    - Ingress
{{- end }}
