{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-istio-enabled-ns
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            istio-injection: enabled
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            istio-injection: enabled
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}