{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-ingressgateway-allow-metric-scraping
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: monitoring
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 15020
          protocol: TCP
  podSelector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  policyTypes:
    - Ingress
{{- end }}
