{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-proxy-to-egress-gateway-{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            {{- if not (eq .Values.revision "") }}
            istio.io/rev: {{ .Values.revision }}
            {{- else }}
            istio-injection: enabled
            {{- end }}
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            {{- if not (eq .Values.revision "") }}
            istio.io/rev: {{ .Values.revision }}
            {{- else }}
            istio-sidecar.istio.io/inject: "true"
            {{- end }}
  podSelector:
    matchLabels:
      istio: egressgateway
  policyTypes:
    - Ingress
{{- end }}
