{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-istio-injected-pods{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            {{- if not (eq .Values.revision "") }}
            istio.io/rev: {{ .Values.revision }}
            {{- else }}
            sidecar.istio.io/inject: "true"
            {{- end }}
      ports:
        - port: 15012
          protocol: TCP
  podSelector:
    matchLabels:
      app: istiod
  policyTypes:
    - Ingress
    - Egress
{{- end }}
