{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-injection-enabled-ns
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            istio-injection: enabled
      ports:
        - port: 15012
          protocol: TCP
  podSelector:
    matchLabels:
      app: istiod
  policyTypes:
    - Ingress
    - Egress
{{- end }}
