{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-webhook
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      istio: pilot
  ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      # Need to determine what port(s) are needed here
  policyTypes:
    - Ingress
{{- end }}
