{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-allow-webhook-api
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: istiod
      istio: pilot
  ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
  policyTypes:
    - Ingress
{{- end }}
