{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-default-deny
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress: []
{{- end }}
