apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: passthrough
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      protocol: HTTP
      number: 8080
    hosts:
    - "keycloak.bigbang.dev"
    tls:
      httpsRedirect: true
  - port:
      name: https
      protocol: HTTPS
      number: 8443
    hosts:
    - "keycloak.bigbang.dev"
    tls:
      mode: PASSTHROUGH