{{- $deployName := "istiod" }}

{{- $sidecarsEnabled := false }}
{{- $pilotEnvVars := dig "pilot" "env" list .Values.values }}
{{- range $envVar := $pilotEnvVars }}
  {{- if and (eq (dig "name" "" $envVar) "ENABLE_NATIVE_SIDECARS") (eq (dig "value" false $envVar) true) }}
    {{- $sidecarsEnabled = true }}
  {{- end }}
{{- end }}

{{- if eq $sidecarsEnabled false }}
{{- if not (eq .Values.revision "") }}{{- $deployName = printf "%s-%s" $deployName .Values.revision }}{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}-hook
  namespace: istio-operator
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
spec:
  template:
    metadata:
      name: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}-hook
      labels:
        app.kubernetes.io/name: istio-controlplane
        app.kubernetes.io/component: "core"
    spec:
      serviceAccountName: istio-operator
      restartPolicy: OnFailure
      tolerations:
      {{- .Values.istiod.tolerations | default (list) | toYaml | nindent 8 }}
      containers:
        - name: hook
          image: "{{ .Values.postInstallHook.image }}:{{ .Values.postInstallHook.tag }}"
          command: ["kubectl"]
          args: ["rollout", "status", {{- printf "deployment/%s" $deployName | quote }}, "-n", "istio-system"]
          securityContext:
            {{- toYaml .Values.postInstallHook.containerSecurityContext | nindent 12 }}
          {{- if .Values.postInstallHook.containerResources.resources }}
          resources:
            requests:
              cpu: {{ .Values.postInstallHook.containerResources.resources.requests.cpu | quote }}
              memory: {{ .Values.postInstallHook.containerResources.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.postInstallHook.containerResources.resources.requests.cpu | quote }}
              memory: {{ .Values.postInstallHook.containerResources.resources.requests.memory | quote }}
          {{- end }}
      securityContext:
        {{- toYaml .Values.postInstallHook.securityContext | nindent 8 }}
{{- end }}
