{{- if  .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-istio-system
  namespace: istio-system
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
