{{- if and .Values.hardened.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-gateway-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      istio: ingressgateway
  rules:
  - from:
    - source:
        ipBlocks: 0.0.0.0/0
{{- end }}
