{{- if and .Values.hardened.enabled .Values.monitoring.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: monitoring-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.hardened.monitoring.namespaces | toYaml | nindent 10 }}
        principals: {{ .Values.hardened.monitoring.principals | toYaml | nindent 10 }}
{{- end }}
